apiVersion: v1
kind: ServiceAccount
metadata:
  name: bff-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
- kind: ServiceAccount
  name: bff-reader
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizer-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimizer-ui
  template:
    metadata:
      labels:
        app: optimizer-ui
    spec:
      serviceAccountName: bff-reader
      imagePullSecrets:
      - name: artifact-registry-secret
      containers:
      - name: ui
        image: __UI_IMAGE_URI__
        env:
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "gke-utilization"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-message-piler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-message-piler
  template:
    metadata:
      labels:
        app: kafka-message-piler
    spec:
      imagePullSecrets:
      - name: artifact-registry-secret
      containers:
      - name: kafka-message-piler
        image: __UI_IMAGE_URI__
        command: ["node", "kafka-piler.js"]
        env:
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "gke-utilization"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: optimizer-ui-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: optimizer-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: optimizer-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: __HOSTNAME__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: optimizer-ui-service
            port:
              number: 80